/**
 * The unpacker inverts the Python packer. The frozen fixture was generated by
 * the actual pack_gaussians_to_binary implementation; expected values below
 * are independently derived from its packed bytes.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import * as pc from 'playcanvas';
import { createLiveSplatStream, PACK_ROTATION_QUAT, unpackSnapshot } from '../src/features/live-splat-stream.js';
import { defaultFeatures } from '../src/features/index.js';

const SH_C0 = 0.28209479177387814;

const fixture = new Uint8Array(readFileSync(new URL('./fixtures/packer-golden.bin', import.meta.url)));

const out = unpackSnapshot(fixture);

assert.equal(out.numSplats, 2);
assert.equal(out.iteration, 4242);

// Independently hand-derived from the frozen packed bytes (first splat):
// fp16 centre [0x4380, 0x4100, 0x3d00] -> [3.75, 2.5, 1.25].
assert.ok(Math.abs(out.properties.x[0] - 3.75) < 1e-2);
assert.ok(Math.abs(out.properties.y[0] - 2.5) < 1e-2);
assert.ok(Math.abs(out.properties.z[0] - 1.25) < 1e-2);

// First scale byte is 129: (129 - 1) / 254 * 21 - 12.
const expectedLogScale = ((129 - 1) / 254) * 21 - 12;
assert.ok(Math.abs(out.properties.scale_0[0] - expectedLogScale) < 1e-3);

// First packed red byte is 135: invert f_dc * SH_C0 + 0.5.
assert.ok(Math.abs(out.properties.f_dc_0[0] - ((135 / 255 - 0.5) / SH_C0)) < 1e-4);

// First packed alpha byte is 204 and opacity is stored pre-sigmoid.
const a = 204 / 255;
assert.ok(Math.abs(out.properties.opacity[0] - (-Math.log(1 / a - 1))) < 1e-4);

// Packed angle 170 maps to 2π/3, so w=cos(π/3)=0.5. Its axis is nonzero.
assert.ok(Math.abs(out.properties.rot_0[0] - 0.5) < 1e-5);
assert.ok(Math.hypot(out.properties.rot_1[0], out.properties.rot_2[0], out.properties.rot_3[0]) > 0.8);

// a foreign magic number is refused
assert.throws(() => unpackSnapshot(new Uint8Array(32)), /magic/i);

// setup/teardown must own the subscription lifecycle. Removing either the
// registration or cleanup branch makes these observable assertions fail.
let registeredTopic;
let registeredHandler;
let unsubscribeCalls = 0;
const feature = createLiveSplatStream({
  subscription: {
    service: {
      on(topic, handler) {
        registeredTopic = topic;
        registeredHandler = handler;
        return () => { unsubscribeCalls += 1; };
      },
    },
    topic: 'gs:job-7',
  },
});
feature.setup({ showSplatData() {} });
assert.equal(registeredTopic, 'gs:job-7');
assert.equal(typeof registeredHandler, 'function');
feature.teardown();
feature.teardown();
assert.equal(unsubscribeCalls, 1);

// The real platform envelope flows all the way from base64 to GSplatData.
let snapshotHandler;
const renders = [];
const liveFeature = createLiveSplatStream({
  subscription: {
    service: { on(_topic, handler) { snapshotHandler = handler; return () => {}; } },
    topic: 'gs:job-7',
  },
});
liveFeature.setup({
  showSplatData(data, rotation) { renders.push({ data, rotation }); },
});
snapshotHandler({
  event: 'gs_snapshot',
  data: { payload: Buffer.from(fixture).toString('base64') },
});
assert.equal(renders.length, 1);
assert.ok(renders[0].data instanceof pc.GSplatData);
assert.equal(renders[0].data.numSplats, 2);
assert.ok(Math.abs(renders[0].data.getProp('x')[0] - 3.75) < 1e-2);
assert.deepEqual(renders[0].rotation, PACK_ROTATION_QUAT);

// A payload-bearing event for another stream must not replace the live scene.
snapshotHandler({
  event: 'gs_cameras',
  data: { payload: Buffer.from(fixture).toString('base64') },
});
assert.equal(renders.length, 1);
liveFeature.teardown();

// A malformed preview is transient transport data, not a viewer-fatal error.
const warn = console.warn;
console.warn = () => {};
try {
  assert.doesNotThrow(() => registeredHandler({ data: { payload: 'not base64' } }));
} finally {
  console.warn = warn;
}

assert.doesNotThrow(() => createLiveSplatStream().setup({ showSplatData() {} }));
assert.doesNotThrow(() => createLiveSplatStream({ subscription: { topic: 'gs:job-7' } }).setup({ showSplatData() {} }));

// A transport registration failure must not abort viewer setup, and its
// teardown must remain safe when registration never produced an unsubscribe.
const registrationFailure = createLiveSplatStream({
  subscription: {
    service: { on() { throw new Error('event bus unavailable'); } },
    topic: 'gs:job-7',
  },
});
const quietWarn = console.warn;
console.warn = () => {};
try {
  assert.doesNotThrow(() => registrationFailure.setup({ showSplatData() {} }));
  assert.doesNotThrow(() => registrationFailure.teardown());
} finally {
  console.warn = quietWarn;
}

// Teardown consumes its subscription before invoking it, so a throwing
// unsubscribe cannot be retried by a later teardown.
let throwingUnsubscribeCalls = 0;
const unsubscribeFailure = createLiveSplatStream({
  subscription: {
    service: {
      on() {
        return () => {
          throwingUnsubscribeCalls += 1;
          throw new Error('event bus cleanup unavailable');
        };
      },
    },
    topic: 'gs:job-7',
  },
});
unsubscribeFailure.setup({ showSplatData() {} });
console.warn = () => {};
try {
  assert.doesNotThrow(() => unsubscribeFailure.teardown());
  assert.doesNotThrow(() => unsubscribeFailure.teardown());
} finally {
  console.warn = quietWarn;
}
assert.equal(throwingUnsubscribeCalls, 1);

const subscription = { service: { on() { return () => {}; } }, topic: 'gs:job-7' };
const featureIds = (options) => defaultFeatures(options).map((feature) => feature.id);
assert.equal(featureIds({ live: false, subscription }).includes('live-splat-stream'), false);
assert.equal(featureIds({ live: true, subscription }).includes('live-splat-stream'), true);

console.log('unpack-check: ok');
